[package]
name = "rustls"
version = "0.16.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"
categories = ["network-programming", "cryptography"]
exclude = ["/sgx/*"]

[dependencies]
base64 = { git = "https://github.com/mesalock-linux/rust-base64-sgx", branch = "v1.0.9-backup" }
log = { git = "https://github.com/mesalock-linux/log-sgx", branch = "v1.0.9-backup", optional = true }
ring = { git = "https://github.com/mesalock-linux/ring-sgx", rev = "v1.0.9-backup" }
sct = { git = "https://github.com/fredfortier/sct.rs", rev = "mesalock_sgx-v1.0.9-backup" }
webpki = { git = "https://github.com/fredfortier/webpki", rev = "mesalock_sgx-v1.0.9-backup" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[features]
default = ["logging", "mesalock_sgx"]
logging = ["log"]
dangerous_configuration = []
quic = []
mesalock_sgx = ["sgx_tstd"]

[dev-dependencies]
#env_logger = "0.6.1"
#log = "0.4.4"
#tempfile = "3.0"
#webpki-roots = { git = "https://github.com/mesalock-linux/webpki-roots", branch = "mesalock_sgx" }
#criterion = "0.2.11"

[[example]]
name = "bogo_shim"
path = "examples/internal/bogo_shim.rs"
required-features = ["dangerous_configuration", "quic"]

[[example]]
name = "trytls_shim"
path = "examples/internal/trytls_shim.rs"

[[example]]
name = "bench"
path = "examples/internal/bench.rs"

[[bench]]
name = "benchmarks"
path = "tests/benchmarks.rs"
harness = false
